[package]
name = "simple-grip"
version = "1.0.0"
edition = "2021"
authors = ["QWxp"]
[dependencies]
walkdir = "2.3.3"
clap = { version = "4.3.4", features = ["color", "derive"] }
tokio = { version = "1.28.2", features = ["full"] }
regex = "1.8.4"
rayon = "1.7.0"